### PR TITLE
Moved Upgrade class from APSIM.Builds into APSIM.Shared

### PR DESCRIPTION
**Pull request by hol430**
This class is now required by the APSIM.Registration repo, so I'm moving it here.

Working on APSIMInitiative/ReferencePanel#15

### CODE REVIEW

**Comment by hol353** [comment]
Actually even though I have merged this, it has occurred to me that we don't use this APSIM.Shared repo anymore. Don't we just use the APSIM.Shared in the APSIMx repo and include that it APSIM.Builds etc?

**Comment by hol430** [comment]
Hmm, you're right. The problem I was trying to solve was creating an 'APSIM downloads' page in the APSIM.Registration repo (as per APSIMInitiative/ReferencePanel#15). This page needs to query some of the APSIM.Builds webservices to fetch a list of available versions, and to faciliate that, I need access to some of the data structures used in APSIM.Builds. I think a better solution might be to just move this webpage into APSIM.Builds.Portal.

**Comment by hol353** [comment]
Or move the Upgrade class into the APSIM.Shared that is in the APSIMx repo.

**Comment by hol430** [comment]
Yeah, maybe that's the simplest solution. It does seem a bit heavy-handed though to have to pull down ApsimX (which is quite fat these days!) just to build APSIM.Builds or APSIM.Registration. If you've already got a local copy of apsimx then I guess it's not such an issue.

I wonder if we should look into using git submodules for this sort of thing, although I guess that would complicate the version control process - and the whole reason we moved away from separate repos was to make it easier for people.

For now, I'll move this into ApsimX/APSIM.Shared when I get back onto this stuff next week.

**Pull request merged**
