### PR TITLE
Changed the way that ProcessWithRedirectedOutput handles child proces…

### PR DESCRIPTION
**Pull request by hol430**
…s' output.

Forgot to make this pull request last week when I was working on the `/m` and `/Verbose` command line switches.

### CODE REVIEW

**Comment by hol353** [comment]
Why do you want this to optionally write to the console? You've changed the meaning of 'redirectOutput'. The existing meaning was to redirect the output/errors to StringBuilders. Your change now means to write to the console. This might cause callers to this to suddenly get console output when they didn't previously.

**Comment by hol430** [comment]
The problem is that it's currently impossible to get live console output from a `ProcessWithRedirectedOutput` (which is used by the multi-process job runner). In order to make the `/Verbose` switch work with the `/m` switch, I will have to either change the behaviour of `ProcessWithRedirectedOutput` or stop using `ProcessWithRedirectedOutput` in the multi-process job runner.

**Comment by hol353** [comment]
You can change the behaviour but don't change the meaning of an argument. Leave 'redirectOutput' as it was and create another flag called 'writeToConsole' or somthing like that.

**Comment by hol353** [comment]
You can then have  'writeToConsole' = false i.e. provide a default so that it doesn't break any callers to the method.

**Comment by hol430** [comment]
Still not sure that this is such a great design decision. If you set `redirectOutput` to false, `writeToConsole` has no effect. It also makes calling the `Start` method a bit clunky. This is the new code from `JobRunnerMultiProcess` in ApsimX:

```csharp
runnerProcess.Start(runnerFileName, null, Directory.GetCurrentDirectory(), verbose, verbose);
```

Finally, does it really make sense to not redirect output? This class is called process ***with redirected output***. If you set `redirectOutput` to false, you've got a process with redirected output without redirected output.

**Pull request merged**
